version: '3.9'

services:
  postgres: 
    image: postgres:12.4
    restart: always 
    environment: 
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quiz-manager-db
    volumes: 
      - ./schema:/docker-entrypoint-initdb.d/
    ports:
      - 5433:5432
  postgres-test-question: 
    image: postgres:12.4
    restart: always 
    environment: 
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test-question-db
    volumes: 
      - ./schema:/docker-entrypoint-initdb.d/
    ports:
      - 5434:5432
  postgres-test-answer: 
    image: postgres:12.4
    restart: always 
    environment: 
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test-answer-db
    volumes: 
      - ./schema:/docker-entrypoint-initdb.d/
    ports:
      - 5435:5432
  postgres-test-quiz: 
    image: postgres:12.4
    restart: always 
    environment: 
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test-quiz-db
    volumes: 
      - ./schema:/docker-entrypoint-initdb.d/
    ports:
      - 5436:5432