version: '3.9'

services: 
  postgres: 
    image: postgres:12.4
    restart: always 
    environment: 
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quiz-manager-db
    volumes: 
      - ./schema:/docker-entrypoint-initdb.d/
    ports:
      - 5433:5432